[workspace]
resolver = "3"
members = [
    "cargo-mutest",
    "mutest-driver",
    "mutest-driver-cli",
    "mutest-emit",
    "mutest-json",
    "mutest-operators",
    "mutest-runtime",
    "tests",
]
